kind: pipeline
name: default

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: seed
    image: mongo
    commands:
      - mongo --host database i1820 mongodb/things_collection_index.js
  - name: test
    image: golang
    environment:
      I1820_TM_DATABASE_URL: "mongodb://database:27017"
    commands:
      - go build
      - go test -v ./...

services:
  - name: database
    image: mongo:latest
