---
kind: pipeline
name: default
type: docker

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all

  - name: migrate
    image: golang
    commands:
      - go build -o I1820
      - ./I1820 migrate
    environment:
      I1820_DATABASE_URL: "mongodb://database:27017"

  - name: seed
    image: mongo
    commands:
      - mongo --host database i1820 .ci/mongo.js

  - name: test
    image: golang
    commands:
      - go build
      - go test -v ./...
    volumes:
      - name: docker-socket
        path: /var/run
    environment:
      I1820_CORE_BROKER_ADDR: "tcp://broker:1883"
      I1820_DATABASE_URL: "mongodb://database:27017"

services:
  - name: docker
    image: dind
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run
  - name: database
    image: mongo:latest
  - name: broker
    image: vernemq/vernemq:latest
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"

volumes:
  - name: docker-socket
    temp: {}
