---
kind: pipeline
name: default
type: docker

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all

  - name: migrate
    image: golang
    commands:
      - go build -o I1820
      - ./I1820 migrate
    environment:
      I1820_DATABASE_URL: "mongodb://database:27017"

  - name: seed
    image: mongo
    commands:
      - mongo --host database i1820 .ci/mongo.js

  - name: test
    image: golang
    commands:
      - go build
      - go test -v ./...
    environment:
      I1820_CORE_BROKER_ADDR: "tcp://broker:1883"
      I1820_DATABASE_URL: "mongodb://database:27017"

  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
    commands:
      - export BUILD_COMMIT_MSG=$DRONE_COMMIT_MESSAGE
      - export BUILD_COMMIT=$DRONE_COMMIT
      - export BUILD_DATE=$(date -R)
    settings:
      username: 1995parham
      password:
        from_secret: docker_password
      repo: i1820/i1820
      tags: latest
      build_args_from_env:
        - BUILD_COMMIT_MSG
        - BUILD_COMMIT
        - BUILD_DATE

services:
  - name: database
    image: mongo:latest
  - name: broker
    image: vernemq/vernemq:latest
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
